### ISSUE TITLE
wrong result in "bitwise-operators" example

### ISSUE THREAD

**Issue by stefanolsenn** [devtut/generate#7]
In the example: [https://devtut.github.io/c/operators.html#bitwise-operators](https://devtut.github.io/c/operators.html#bitwise-operators)

It states that the bitwise operation is 32.
`c = a & b;              /* 32 = 0001 0000 */ `
While the binary representation is correct, the decimal representation should be 16.

**Comment by pollmix** [comment]
Solved now, thanks
